apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: drupal-fss-pvc
 namespace: drupal-fss
spec:
 storageClassName: drupal-fss-sc
 accessModes:
 - ReadWriteMany
 resources:
  requests:
 # Although storage is provided here it is not used for FSS file systems
    storage: 100Gi
 volumeName: drupal-fss-pv
